### PR TITLE
utils.widgets: fix handling of move events

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This was discovered by Francois and it would make sense to merge quickly

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Hopefully the code is now explicit enough to allow a review.

**Comment by MatthieuDartiailh** [comment]
Thanks @leghtas

**Comment by MatthieuDartiailh** [comment]
@lcontami should I wait for your review ?

**Comment by lcontami** [comment]
I did not test it. Looking at the code it looked fine although I can't say I understood everything. Added comments are definitely useful!

**Comment by MatthieuDartiailh** [comment]
Merging then as they are more stuff to review and this got enough attention already

**Pull request merged**
